#!/usr/bin/env python3
import colors as c
import random
print("""
welcome to magic eight ball
enter your question below
""")

answers = ['yes',
'no',
'maybe',
'it is ceatain',
'reply hazy try again',
'outlook good',
'don\'t count on it',
'my reply is no',
'better not tell you now',
'very doubtful',
'do not know',
'figure it out your self']

def ask(prompt):
    answer = input(prompt).strip().lower()
    return answer
def bye():
    print(c.rc() + "see you again" + c.x)
    exit(0)

try:
    while True:
        question = ask('--> ')
        if "death" in question or "die" in question:
            print(c.rc() + "yes" + c.x)
        elif "love" in question:
            print(c.y + "maybe" + c.x)
        elif "hate"in question:    
            print(c.g + "do not know")
        elif "outlook bad" in question: 
            print(c.b + "can't tell you know")
        elif "great" in question:
            print(c.r + "to much harsh questions")
        elif "bye" in question:
            bye()
        else:
            answer = random.choice(answers)
            print(answer)

except KeyboardInterrupt:
    bye()


